from variable_functions import save_variable, get_variable
import os
import sqlite3
from dotenv import load_dotenv
load_dotenv()
con = sqlite3.connect(os.getenv("DB_NAME")) 
cur = con.cursor()
program = os.getenv("PROGRAM_NAME")
variables = os.getenv("VARIABLES_NAME")
con.execute(f"DELETE FROM {variables}")
con.commit()
rec = os.getenv("RECURSION")
save_variable(["abba", 3, "baba"], "a")
print(get_variable("a"))
print()
save_variable(1, rec)
save_variable(2, "a")
print(get_variable("a"))
print()
save_variable(3, "b")
print(get_variable("a"))
print()
print(get_variable("b"))
print()
save_variable(0, rec)
print(get_variable("a"))
print()
print(get_variable("b"))
print()
save_variable(3, "a")
save_variable(4, "b")